name: Publish
on:
  release:
    branches:
      - master
    types:
      - published
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build
        run: uv build
      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: uv publish
