name: Publish
on:
  release:
    branches:
      - master
jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1.1.1
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_token }}
        run: poetry publish --build
