name: Run Tests
on: 
  push:
  pull-request:
  schedule:
    - cron: "1 1 1 * *"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --user poetry
          poetry install -E pandas
          poetry run pytest
